ALTER TABLE blog_info
    ADD COLUMN IF NOT EXISTS blog_title_mr VARCHAR(255),
    ADD COLUMN IF NOT EXISTS blog_summary_mr VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS blog_content_mr TEXT,
    ADD COLUMN IF NOT EXISTS blog_author_mr VARCHAR(255),
    ADD COLUMN IF NOT EXISTS tags_mr VARCHAR(255),
    ADD COLUMN IF NOT EXISTS category_mr VARCHAR(255);
